spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

cards:
  message: "Welcome to fincrest cards related prod APIs"
  contactDetails:
    name: "Reine Aishwarya - Product Owner"
    email: "aishwarya@fincrest.com"
  onCallSupport:
    - (777) 321-2309
    - (777) 486-0476