services:
  accounts:
    image: "shobhit6402/accounts:s1"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - fincrest
  loans:
    image: "shobhit6402/loans:s1"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - fincrest
  cards:
    image: "shobhit6402/cards:s1"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - fincrest
networks:
  fincrest:
    driver: "bridge"