spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

loans:
  message: "Welcome to fincrest loans related QA APIs"
  contactDetails:
    name: "Smitha Ray - QA Lead"
    email: "smitha@fincrest.com"
  onCallSupport:
    - (666) 265-3787
    - (666) 376-0938