spring:
  application:
    name: "configserver"
  profiles:
#    active: "native"
    active: "git"
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/shobhit7390/fincrest-config.git"
          default-label: "main"
          timeout: 5
          clone-on-start: true
          force-pull: true
#        native:
#          search-locations: "file:///Users/shobhityadav/config"
#          search-locations: "classpath:/config"

server:
  port: 8071